version: '3.8'

services:

  frontend:
    container_name: frontend-recode
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    container_name: backend-recode
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-recode
    restart: always
    environment:
      POSTGRES_DB: recode_db
      POSTGRES_USER: recode_user
      POSTGRES_PASSWORD: recode_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
